<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDtaQBqN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDtaQBqN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDtaQBqN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDtaQBqN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDtaQBqN\App_KernelDevDebugContainer([
    'container.build_hash' => 'DtaQBqN',
    'container.build_id' => '3663edc1',
    'container.build_time' => 1685910879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDtaQBqN');
